//Auth
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ERROR = "ERROR";
export const FORGET = "FORGET";
export const TOGGLE_AUTH_LOADING = "TOGGLE_AUTH_LOADING";
export const CURRENT_USER = "CURRENT_USER";

export const TOGGLE_SITE_LOADING = "TOGGLE_SITE_LOADING";

//Company
export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_ADMIN = "FETCH_ADMIN";
export const TOGGLE_ADMIN_SUSPEND_STATUS = "TOGGLE_ADMIN_SUSPEND_STATUS";
export const TOGGLE_EXTEND_SUBS_STATUS = "TOGGLE_EXTEND_SUBS_STATUS";

//Counter
export const FETCH_COUNTERS = "FETCH_COUNTERS";
export const FETCH_COUNTER = "FETCH_COUNTER";
export const FETCH_DIVISIONS = "FETCH_DIVISIONS";
export const FETCH_DISTRICTS = "FETCH_DISTRICTS";
export const FETCH_BUSES = "FETCH_BUSES";
export const FETCH_BUS = "FETCH_BUS";
export const DELETE_BUS = "DELETE_BUS";
export const FETCH_SCHEDULES = "FETCH_SCHEDULES";
export const FETCH_SCHEDULE = "FETCH_SCHEDULE";

//fare
export const FETCH_FARES = "FETCH_FARES";
export const FETCH_FARE = "FETCH_FARE";
export const DELETE_FARE = "DELETE_FARE";
export const TOGGLE_FARE_VALIDATION_ERROR = "TOGGLE_FARE_VALIDATION_ERROR";

//file
export const UPLOAD_FILE = "UPLOAD_FILE";

//driver and staff
export const FETCH_DRIVERS = "FETCH_DRIVERS";
export const FETCH_DRIVER = "FETCH_DRIVER";
export const DELETE_DRIVER = "DELETE_DRIVER";

export const FETCH_STAFFS = "FETCH_STAFFS";
export const FETCH_STAFF = "FETCH_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";
