//Auth
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ERROR = "ERROR";
export const FORGET = "FORGET";
export const TOGGLE_AUTH_LOADING = "TOGGLE_AUTH_LOADING";
export const CURRENT_USER = "CURRENT_USER";

//Company
export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_ADMIN = "FETCH_ADMIN";
export const TOGGLE_ADMIN_SUSPEND_STATUS = "TOGGLE_ADMIN_SUSPEND_STATUS";
export const TOGGLE_EXTEND_SUBS_STATUS = "TOGGLE_EXTEND_SUBS_STATUS";

//Counter
export const FETCH_COUNTERS = "FETCH_COUNTERS";
export const FETCH_DIVISIONS = "FETCH_DIVISIONS";
export const FETCH_DISTRICTS = "FETCH_DISTRICTS";
export const FETCH_BUSES = "FETCH_BUSES";
export const FETCH_BUS = "FETCH_BUS";
export const DELETE_BUS = "DELETE_BUS";
export const FETCH_SCHEDULES = "FETCH_SCHEDULES";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
