//Auth
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTH_VALIDATE_ERROR = "AUTH_VALIDATE_ERROR";
export const FORGET = "FORGET";
export const TOGGLE_BUTTON_LOADING = "TOGGLE_BUTTON_LOADING";
export const CURRENT_USER = "CURRENT_USER";

export const TOGGLE_SITE_LOADING = "TOGGLE_SITE_LOADING";

//Company
export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const COMPANY_VALIDATE_ERROR = "COMPANY_VALIDATE_ERROR";

//Admin
export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_ADMIN = "FETCH_ADMIN";
export const ADMIN_VALIDATE_ERROR = "ADMIN_VALIDATE_ERROR";
export const TOGGLE_ADMIN_SUSPEND_STATUS = "TOGGLE_ADMIN_SUSPEND_STATUS";
export const TOGGLE_EXTEND_SUBS_STATUS = "TOGGLE_EXTEND_SUBS_STATUS";

//Counter
export const FETCH_COUNTERS = "FETCH_COUNTERS";
export const FETCH_COUNTER = "FETCH_COUNTER";
export const COUNTER_VALIDATE_ERROR = "COUNTER_VALIDATE_ERROR";

//Division and district
export const FETCH_DIVISIONS = "FETCH_DIVISIONS";
export const FETCH_DISTRICTS = "FETCH_DISTRICTS";

//Bus
export const FETCH_BUSES = "FETCH_BUSES";
export const FETCH_BUS = "FETCH_BUS";
export const DELETE_BUS = "DELETE_BUS";
export const UPDATE_BUS = "UPDATE_BUS";
export const BUS_VALIDATE_ERROR = "BUS_VALIDATE_ERROR";
export const FETCH_BUS_BY_TYPE = "FETCH_BUS_BY_TYPE";

//Schedule
export const FETCH_SCHEDULES = "FETCH_SCHEDULES";
export const FETCH_SCHEDULE = "FETCH_SCHEDULE";
export const SCHEDULE_VALIDATE_ERROR = "SCHEDULE_VALIDATE_ERROR";

//fare
export const FETCH_FARES = "FETCH_FARES";
export const FETCH_FARE = "FETCH_FARE";
export const DELETE_FARE = "DELETE_FARE";
export const FARE_VALIDATE_ERROR = "FARE_VALIDATE_ERROR";

//file
export const UPLOAD_FILE = "UPLOAD_FILE";

//driver and staff
export const FETCH_DRIVERS = "FETCH_DRIVERS";
export const FETCH_DRIVER = "FETCH_DRIVER";
export const DELETE_DRIVER = "DELETE_DRIVER";
export const STAFF_VALIDATE_ERROR = "STAFF_VALIDATE_ERROR";

export const FETCH_STAFFS = "FETCH_STAFFS";
export const FETCH_STAFF = "FETCH_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";

//Track
export const FETCH_TRACKS = "FETCH_TRACKS";
export const FETCH_TRACK = "FETCH_TRACK";
export const DELETE_TRACK = "DELETE_TRACK";
export const TRACK_VALIDATE_ERROR = "TRACK_VALIDATE_ERROR";

//counter
export const FETCH_ROUTES = "FETCH_ROUTES";
export const SEARCH_ROUTE = "SEARCH_ROUTE";
export const ROUTE_ID = "ROUTE_ID";
export const ASSIGN_BUS_VALIDATE_ERROR = "ASSIGN_BUS_VALIDATE_ERROR";
export const ASSIGN_BUS_DIALOG = "ASSIGN_BUS_DIALOG";
export const ASSIGN_BUS = "ASSIGN_BUS";

export const SEARCH_HISTORY = "SEARCH_HISTORY";
export const CONFIRM_TICKET = "CONFIRM_TICKET";
export const UPDATE_COACH_BY_CONFIRM_TICKET = "UPDATE_COACH_BY_CONFIRM_TICKET";
export const SEARCH_TICKET = "SEARCH_TICKET";

export const FETCH_SEATS = "FETCH_SEATS";

//user
export const SEARCH_COACHES = "SEARCH_COACHES";
export const SEARCH_COACH_HISTORY = "SEARCH_COACH_HISTORY";
